[package]
name = "r2sleigh-lift"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sleigh to r2il translator"

[dependencies]
r2il = { path = "../r2il" }
r2source = { path = "../r2source" }
libsla.workspace = true
thiserror.workspace = true

[dependencies.sleigh-config]
workspace = true
optional = true

[features]
default = []
x86 = ["sleigh-config/x86"]
arm = ["sleigh-config/ARM", "sleigh-config/AARCH64"]
mips = ["sleigh-config/MIPS"]
riscv = ["sleigh-config/RISCV"]

[dev-dependencies]
sleigh-config = { workspace = true, features = ["AARCH64"] }
